### ISSUE TITLE
I have tried everything but Film VFI always missing

### ISSUE THREAD

**Issue by dkamajix** [Fannovel16/ComfyUI-Frame-Interpolation#13]
![image](https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/assets/143731847/6350ebe0-b2c6-4553-8aa1-5288e9fec46f)

I have tried updating comfy and all extensions. I tried following your incompatible instructions using local database.. I un installed the extension and reinstalled. Im not sure how to get it working. I have many extensions that have no problems. any help?

**Comment by Fannovel16** [comment]
@dkamajix Can you post the log of the command-line running ComfyUI?

**Comment by screan** [comment]
here is my log with the same issue `Traceback (most recent call last):
  File "C:\Users\name\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\jr\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved-dev\__init__.py", line 2, in <module>
    from .animatediff.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\jr\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved-dev\animatediff\nodes.py", line 18, in <module>
    from .motion_module import InjectorVersion, eject_params_from_model, get_injected_mm_params, inject_params_into_model, load_motion_lora, load_motion_module
  File "C:\Users\jr\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved-dev\animatediff\motion_module.py", line 11, in <module>
    from .motion_module_ad import AnimDiffMotionWrapper, has_mid_block
  File "C:\Users\jr\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved-dev\animatediff\motion_module_ad.py", line 9, in <module>
    from .motion_utils import GenericMotionWrapper, InjectorVersion, BlockType, CrossAttentionMM
  File "C:\Users\jr\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved-dev\animatediff\motion_utils.py", line 5, in <module>
    from comfy.ldm.modules.attention import CrossAttentionBirchSan, CrossAttentionDoggettx, CrossAttentionPytorch, FeedForward, CrossAttention, MemoryEfficientCrossAttention
ImportError: cannot import name 'CrossAttentionBirchSan' from 'comfy.ldm.modules.attention' (C:\Users\jr\AI\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\attention.py)

Cannot import C:\Users\jr\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved-dev module for custom nodes: cannot import name 'CrossAttentionBirchSan' from 'comfy.ldm.modules.attention' (C:\Users\jr\AI\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\attention.py)
Traceback (most recent call last):
  File "C:\Users\jr\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\jr\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\__init__.py", line 9, in <module>
    from models.gmfss_fortuna import GMFSS_Fortuna_VFI
  File "C:\Users\jr\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\gmfss_fortuna\__init__.py", line 7, in <module>
    from .GMFSS_Fortuna_arch import Model as GMFSS
  File "C:\Users\jr\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\gmfss_fortuna\GMFSS_Fortuna_arch.py", line 29, in <module>
    from models.ops import softsplat
  File "C:\Users\jr\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\ops\__init__.py", line 21, in <module>
    from .cupy_ops import softsplat, ModuleSoftsplat, FunctionSoftsplat, softsplat_func, costvol_func, sepconv_func, init, batch_edt, FunctionAdaCoF, ModuleCorrelation, FunctionCorrelation, _FunctionCorrelation
  File "C:\Users\jr\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\ops\cupy_ops\__init__.py", line 1, in <module>
    from .costvol import *
  File "C:\Users\jr\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\ops\cupy_ops\costvol.py", line 1, in <module>
    from .utils import cuda_kernel, cuda_launch, cuda_int32
  File "C:\Users\jr\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\ops\cupy_ops\utils.py", line 1, in <module>
    import cupy
ModuleNotFoundError: No module named 'cupy'

Cannot import C:\Users\jr\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation module for custom nodes: No module named 'cupy'`

**Comment by screan** [comment]
> @dkamajix Can you post the log of the terminal running ComfyUI?

same issue here:

````
Traceback (most recent call last):
  File "C:\Users\jr\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\jr\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\__init__.py", line 9, in <module>
    from models.gmfss_fortuna import GMFSS_Fortuna_VFI
  File "C:\Users\jr\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\gmfss_fortuna\__init__.py", line 7, in <module>
    from .GMFSS_Fortuna_arch import Model as GMFSS
  File "C:\Users\jr\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\gmfss_fortuna\GMFSS_Fortuna_arch.py", line 29, in <module>
    from models.ops import softsplat
  File "C:\Users\jr\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\ops\__init__.py", line 21, in <module>
    from .cupy_ops import softsplat, ModuleSoftsplat, FunctionSoftsplat, softsplat_func, costvol_func, sepconv_func, init, batch_edt, FunctionAdaCoF, ModuleCorrelation, FunctionCorrelation, _FunctionCorrelation
  File "C:\Users\jr\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\ops\cupy_ops\__init__.py", line 1, in <module>
    from .costvol import *
  File "C:\Users\jr\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\ops\cupy_ops\costvol.py", line 1, in <module>
    from .utils import cuda_kernel, cuda_launch, cuda_int32
  File "C:\Users\jr\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\ops\cupy_ops\utils.py", line 1, in <module>
    import cupy
ModuleNotFoundError: No module named 'cupy'

Cannot import C:\Users\jr\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation module for custom nodes: No module named 'cupy'
````

**Comment by Fannovel16** [comment]
@screan @dkamajix Try using `install.bat`

**Comment by Fannovel16** [comment]
@here Can yall try the latest commit?

**Comment by dkamajix** [comment]
how do you run the latest commit?
here is my terminal:

X:\STABLE_DIFFUSION\COMFY>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI start up time: 2023-10-12 10:39:09.388896

Prestartup times for custom nodes:
   0.0 seconds: X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8191 MB, total RAM 131015 MB
xformers version: 0.0.21
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
Adding extra search path checkpoints X:\STABLE_DIFFUSION\SD_MODELS\CHECKPOINTS
Adding extra search path configs X:\STABLE_DIFFUSION\SD_MODELS\models/Stable-diffusion
Adding extra search path vae X:\STABLE_DIFFUSION\SD_MODELS\VAE
Adding extra search path loras X:\STABLE_DIFFUSION\SD_MODELS\LORAS
Adding extra search path loras X:\STABLE_DIFFUSION\SD_MODELS\models/LyCORIS
Adding extra search path upscale_models X:\STABLE_DIFFUSION\SD_MODELS\ERSGAN
Adding extra search path upscale_models X:\STABLE_DIFFUSION\SD_MODELS\models/RealESRGAN
Adding extra search path upscale_models X:\STABLE_DIFFUSION\SD_MODELS\models/SwinIR
Adding extra search path embeddings X:\STABLE_DIFFUSION\SD_MODELS\embeddings
Adding extra search path hypernetworks X:\STABLE_DIFFUSION\SD_MODELS\models/hypernetworks
Adding extra search path controlnet X:\STABLE_DIFFUSION\SD_MODELS\models/ControlNet
Using xformers cross attention
Traceback (most recent call last):
  File "X:\STABLE_DIFFUSION\COMFY\ComfyUI\nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\__init__.py", line 9, in <module>
    from models.gmfss_fortuna import GMFSS_Fortuna_VFI
  File "X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\gmfss_fortuna\__init__.py", line 7, in <module>
    from .GMFSS_Fortuna_arch import Model as GMFSS
  File "X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\gmfss_fortuna\GMFSS_Fortuna_arch.py", line 29, in <module>
    from models.ops import softsplat
  File "X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\ops\__init__.py", line 21, in <module>
    from .cupy_ops import softsplat, ModuleSoftsplat, FunctionSoftsplat, softsplat_func, costvol_func, sepconv_func, init, batch_edt, FunctionAdaCoF, ModuleCorrelation, FunctionCorrelation, _FunctionCorrelation
  File "X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\ops\cupy_ops\__init__.py", line 1, in <module>
    from .costvol import *
  File "X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\ops\cupy_ops\costvol.py", line 1, in <module>
    from .utils import cuda_kernel, cuda_launch, cuda_int32
  File "X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\ops\cupy_ops\utils.py", line 1, in <module>
    import cupy
ModuleNotFoundError: No module named 'cupy'

Cannot import X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation module for custom nodes: No module named 'cupy'
### Loading: ComfyUI-Impact-Pack (V4.18.6)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.2.4)
### Loading: ComfyUI-Inspire-Pack (V0.27.1)
### Loading: ComfyUI-Manager (V0.34)
### ComfyUI Revision: 1555 [8cc75c64] | Released on '2023-10-11'
moviepy is already installed.
cv2 is already installed.
git is already installed.
zipfile is already installed.
skbuild is already installed.
Loaded 3.x/4.x HD model.
Traceback (most recent call last):
  File "X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\ComfyUI-N-Nodes\__init__.py", line 90, in <module>
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\ComfyUI-N-Nodes\py\gptcpp_node.py", line 3, in <module>
    from llama_cpp import Llama
ModuleNotFoundError: No module named 'llama_cpp'
Comfyroll Custom Nodes: Loaded
Registered sys.path: ['X:\\STABLE_DIFFUSION\\COMFY\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\__init__.py', 'X:\\STABLE_DIFFUSION\\COMFY\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_pycocotools', 'X:\\STABLE_DIFFUSION\\COMFY\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_oneformer', 'X:\\STABLE_DIFFUSION\\COMFY\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_mmpkg', 'X:\\STABLE_DIFFUSION\\COMFY\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_midas_repo', 'X:\\STABLE_DIFFUSION\\COMFY\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_detectron2', 'X:\\STABLE_DIFFUSION\\COMFY\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\controlnet_aux', 'X:\\STABLE_DIFFUSION\\COMFY\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src', 'X:\\STABLE_DIFFUSION\\COMFY\\ComfyUI\\custom_nodes\\ComfyUI_Comfyroll_CustomNodes\\comfy', 'X:\\STABLE_DIFFUSION\\COMFY\\ComfyUI\\custom_nodes\\ComfyUI_Comfyroll_CustomNodes\\comfy', 'X:\\STABLE_DIFFUSION\\COMFY\\ComfyUI\\custom_nodes\\ComfyUI-Frame-Interpolation', 'X:\\STABLE_DIFFUSION\\COMFY\\python_embeded\\lib\\site-packages\\git\\ext\\gitdb', 'X:\\STABLE_DIFFUSION\\COMFY\\ComfyUI\\custom_nodes\\ComfyUI-Custom-Scripts', WindowsPath('X:/STABLE_DIFFUSION/COMFY/ComfyUI'), 'X:\\STABLE_DIFFUSION\\COMFY\\ComfyUI\\comfy', 'X:\\STABLE_DIFFUSION\\COMFY\\ComfyUI', 'X:\\STABLE_DIFFUSION\\COMFY\\python_embeded\\python310.zip', 'X:\\STABLE_DIFFUSION\\COMFY\\python_embeded', 'X:\\STABLE_DIFFUSION\\COMFY\\python_embeded\\lib\\site-packages', 'X:\\STABLE_DIFFUSION\\COMFY\\python_embeded\\lib\\site-packages\\win32', 'X:\\STABLE_DIFFUSION\\COMFY\\python_embeded\\lib\\site-packages\\win32\\lib', 'X:\\STABLE_DIFFUSION\\COMFY\\python_embeded\\lib\\site-packages\\Pythonwin', 'X:\\STABLE_DIFFUSION\\COMFY\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\modules', 'X:\\STABLE_DIFFUSION\\COMFY\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\impact_subpack', '../..', 'X:\\STABLE_DIFFUSION\\COMFY\\ComfyUI\\custom_nodes\\ComfyUI-N-Nodes\\libs\\rifle']
FizzleDorf Custom Nodes: Loaded
Traceback (most recent call last):
  File "X:\STABLE_DIFFUSION\COMFY\ComfyUI\nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'X:\\STABLE_DIFFUSION\\COMFY\\ComfyUI\\custom_nodes\\ComfyUI_IPAdapter_plus\\__init__.py'

Cannot import X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus module for custom nodes: [Errno 2] No such file or directory: 'X:\\STABLE_DIFFUSION\\COMFY\\ComfyUI\\custom_nodes\\ComfyUI_IPAdapter_plus\\__init__.py'
X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\failfast-comfyui-extensions\extensions
X:\STABLE_DIFFUSION\COMFY\ComfyUI\web\extensions\failfast-comfyui-extensions
Traceback (most recent call last):
  File "X:\STABLE_DIFFUSION\COMFY\ComfyUI\nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'X:\\STABLE_DIFFUSION\\COMFY\\ComfyUI\\custom_nodes\\frame-interpolation\\__init__.py'

Cannot import X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\frame-interpolation module for custom nodes: [Errno 2] No such file or directory: 'X:\\STABLE_DIFFUSION\\COMFY\\ComfyUI\\custom_nodes\\frame-interpolation\\__init__.py'
Traceback (most recent call last):
  File "X:\STABLE_DIFFUSION\COMFY\ComfyUI\nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'X:\\STABLE_DIFFUSION\\COMFY\\ComfyUI\\custom_nodes\\GMFSS\\__init__.py'

Cannot import X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\GMFSS module for custom nodes: [Errno 2] No such file or directory: 'X:\\STABLE_DIFFUSION\\COMFY\\ComfyUI\\custom_nodes\\GMFSS\\__init__.py'
Downloading anime face detector...
Failed to download lbpcascade_animeface.xml so please download it yourself.
[Power Noise Suite]: 🦚🦚🦚    MooOoo!!! 🦚🦚🦚
[Power Noise Suite]: Tamed 11 wild nodes.
Traceback (most recent call last):
  File "X:\STABLE_DIFFUSION\COMFY\ComfyUI\nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'X:\\STABLE_DIFFUSION\\COMFY\\ComfyUI\\custom_nodes\\VFIformer\\__init__.py'

Cannot import X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\VFIformer module for custom nodes: [Errno 2] No such file or directory: 'X:\\STABLE_DIFFUSION\\COMFY\\ComfyUI\\custom_nodes\\VFIformer\\__init__.py'
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 196 nodes successfully.

        "Don't be afraid to give up the good to go for the great." - John D. Rockefeller

Traceback (most recent call last):
  File "X:\STABLE_DIFFUSION\COMFY\ComfyUI\nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'X:\\STABLE_DIFFUSION\\COMFY\\ComfyUI\\custom_nodes\\web\\__init__.py'

Cannot import X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\web module for custom nodes: [Errno 2] No such file or directory: 'X:\\STABLE_DIFFUSION\\COMFY\\ComfyUI\\custom_nodes\\web\\__init__.py'

Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\web
   0.0 seconds (IMPORT FAILED): X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds (IMPORT FAILED): X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\GMFSS
   0.0 seconds (IMPORT FAILED): X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\VFIformer
   0.0 seconds (IMPORT FAILED): X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\frame-interpolation
   0.0 seconds: X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\ComfyUI-Image-Selector
   0.0 seconds: X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\PowerNoiseSuite
   0.0 seconds: X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\stability-ComfyUI-nodes
   0.0 seconds: X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\ComfyUi_NNLatentUpscale
   0.0 seconds: X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\images-grid-comfy-plugin
   0.0 seconds: X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\ComfyUI-Loopchain
   0.0 seconds: X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\IPAdapter-ComfyUI
   0.0 seconds: X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds: X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.1 seconds: X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.1 seconds: X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.1 seconds: X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.1 seconds: X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.1 seconds: X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.2 seconds (IMPORT FAILED): X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.2 seconds: X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\ComfyUI_smZNodes
   0.6 seconds: X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\ComfyUI-Manager
   0.9 seconds: X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\failfast-comfyui-extensions
   1.2 seconds: X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   2.2 seconds: X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\ComfyUI-N-Nodes
   2.7 seconds: X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\comfy_controlnet_preprocessors
   3.2 seconds: X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   3.2 seconds: X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: X:\STABLE_DIFFUSION\COMFY\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
Temporary folder X:\STABLE_DIFFUSION\COMFY\ComfyUI\temp\n-suite\frames has been emptied.

**Comment by Fannovel16** [comment]
@dkamajix Try reinstalling ComfyUI-Frame-Interpolation
