### ISSUE TITLE
When loading the graph, the following node types were not found: FILM VFI

### ISSUE THREAD

**Issue by 4lt3r3go** [Fannovel16/ComfyUI-Frame-Interpolation#16]
it was working ok, untill i had to reinstall everything. now this 

![image](https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/assets/44883288/89e64d45-d825-4a70-a7ca-8a948c4e8133)

**Comment by FigittyFau** [comment]
What does it mean?

**Comment by 4lt3r3go** [comment]
ok ty but i still get that the module is missing

**Comment by boricuapab** [comment]
Running into same issue was working until I decided to update comfy today to pickup the cuda 12 implementation

```
Checking cupy...
Uninstall cupy if existed...
WARNING: Skipping cupy-wheel as it is not installed.
WARNING: Skipping cupy-cuda102 as it is not installed.
WARNING: Skipping cupy-cuda110 as it is not installed.
WARNING: Skipping cupy-cuda111 as it is not installed.
Found existing installation: cupy-cuda11x 12.2.0
Uninstalling cupy-cuda11x-12.2.0:
  Successfully uninstalled cupy-cuda11x-12.2.0
ERROR: Exception:
Traceback (most recent call last):
  File "C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\commands\uninstall.py", line 110, in run
    uninstall_pathset.commit()
  File "C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\req\req_uninstall.py", line 432, in commit
    self._moved_paths.commit()
  File "C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\req\req_uninstall.py", line 278, in commit
    save_dir.cleanup()
  File "C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\utils\temp_dir.py", line 173, in cleanup
    rmtree(self._path)
  File "C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 291, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 381, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 327, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 160, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "concurrent\futures\_base.py", line 449, in result
  File "concurrent\futures\_base.py", line 401, in __get_result
  File "C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 384, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\utils\misc.py", line 130, in rmtree
    shutil.rmtree(dir, ignore_errors=ignore_errors, onerror=rmtree_errorhandler)
  File "shutil.py", line 759, in rmtree
  File "shutil.py", line 617, in _rmtree_unsafe
  File "shutil.py", line 622, in _rmtree_unsafe
  File "shutil.py", line 620, in _rmtree_unsafe
PermissionError: [WinError 5] Access is denied: 'C:\\sdComfyUI\\ComfyUI_windows_portable\\python_embeded\\Lib\\site-packages\\~~py\\cuda\\device.cp311-win_amd64.pyd'
Installing cupy...
WARNING: Ignoring invalid distribution ~ (C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages)
Collecting cupy-cuda11x
  Obtaining dependency information for cupy-cuda11x from https://files.pythonhosted.org/packages/b2/a9/569c6f4eb5bbd12646befedce5382ddc1e710a0dc4964e7e085f7987529b/cupy_cuda11x-12.2.0-cp311-cp311-win_amd64.whl.metadata
  Using cached cupy_cuda11x-12.2.0-cp311-cp311-win_amd64.whl.metadata (2.7 kB)
Requirement already satisfied: numpy<1.27,>=1.20 in c:\sdcomfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from cupy-cuda11x) (1.25.2)
Requirement already satisfied: fastrlock>=0.5 in c:\sdcomfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from cupy-cuda11x) (0.8.2)
Using cached cupy_cuda11x-12.2.0-cp311-cp311-win_amd64.whl (70.2 MB)
WARNING: Ignoring invalid distribution ~ (C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages)
Installing collected packages: cupy-cuda11x
Successfully installed cupy-cuda11x-12.2.0
Press any key to continue . . .

**Comment by dkamajix** [comment]
Im getting this again after a fresh install as well.
Its fixed in my older copy but in my fresh comfy batch getting red box for film vfi

**Comment by pacmanincarnate** [comment]
Not sure if it's related, but I'm getting RIFE VFI not found. Can't use this process without that one, unfortunately.
