### ISSUE TITLE
WIN 10 Cupy Build Issue

### ISSUE THREAD

**Issue by boricuapab** [Fannovel16/ComfyUI-Frame-Interpolation#19]
Getting some cupy wheel build errors

```
Using pytorch cross attention
Traceback (most recent call last):
  File "C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cupy\__init__.py", line 17, in <module>
    from cupy import _core  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cupy\_core\__init__.py", line 3, in <module>
    from cupy._core import core  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "cupy\_core\core.pyx", line 1, in init cupy._core.core
  File "C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cupy\cuda\__init__.py", line 8, in <module>
    from cupy.cuda import compiler  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cupy\cuda\compiler.py", line 13, in <module>
    from cupy.cuda import device
  File "cupy\cuda\device.pyx", line 1, in init cupy.cuda.device
ImportError: DLL load failed while importing runtime: The specified module could not be found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\sdComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\sdComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\__init__.py", line 9, in <module>
    from models.gmfss_fortuna import GMFSS_Fortuna_VFI
  File "C:\sdComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\gmfss_fortuna\__init__.py", line 7, in <module>
    from .GMFSS_Fortuna_arch import Model as GMFSS
  File "C:\sdComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\gmfss_fortuna\GMFSS_Fortuna_arch.py", line 29, in <module>
    from models.ops import softsplat
  File "C:\sdComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\ops\__init__.py", line 21, in <module>
    from .cupy_ops import softsplat, ModuleSoftsplat, FunctionSoftsplat, softsplat_func, costvol_func, sepconv_func, init, batch_edt, FunctionAdaCoF, ModuleCorrelation, FunctionCorrelation, _FunctionCorrelation
  File "C:\sdComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\ops\cupy_ops\__init__.py", line 1, in <module>
    from .costvol import *
  File "C:\sdComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\ops\cupy_ops\costvol.py", line 1, in <module>
    from .utils import cuda_kernel, cuda_launch, cuda_int32
  File "C:\sdComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\ops\cupy_ops\utils.py", line 1, in <module>
    import cupy
  File "C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cupy\__init__.py", line 19, in <module>
    raise ImportError(f'''
ImportError:
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

CUDA Path: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1
DLL dependencies:
  KERNEL32.dll -> C:\WINDOWS\System32\KERNEL32.DLL
  MSVCP140.dll -> C:\WINDOWS\SYSTEM32\msvcp140.dll
  VCRUNTIME140.dll -> C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\VCRUNTIME140.dll
  api-ms-win-crt-convert-l1-1-0.dll -> C:\WINDOWS\System32\ucrtbase.dll
  api-ms-win-crt-environment-l1-1-0.dll -> C:\WINDOWS\System32\ucrtbase.dll
  api-ms-win-crt-filesystem-l1-1-0.dll -> C:\WINDOWS\System32\ucrtbase.dll
  api-ms-win-crt-heap-l1-1-0.dll -> C:\WINDOWS\System32\ucrtbase.dll
  api-ms-win-crt-runtime-l1-1-0.dll -> C:\WINDOWS\System32\ucrtbase.dll
  api-ms-win-crt-stdio-l1-1-0.dll -> C:\WINDOWS\System32\ucrtbase.dll
  cuTENSOR.dll -> not found
  cublas64_11.dll -> not found
  cudart64_110.dll -> not found
  cudnn64_8.dll -> C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\lib\cudnn64_8.dll
  cufft64_10.dll -> not found
  curand64_10.dll -> C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\lib\curand64_10.dll
  cusolver64_11.dll -> C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\lib\cusolver64_11.dll
  cusparse64_11.dll -> not found
  nvcuda.dll -> C:\WINDOWS\SYSTEM32\nvcuda.dll
  nvrtc64_112_0.dll -> not found
  python311.dll -> C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\python311.dll

Original error:
  ImportError: DLL load failed while importing runtime: The specified module could not be found.
================================================================


Cannot import C:\sdComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation module for custom nodes:
================================================================
Failed to import CuPy.

If you installed CuPy via wheels (cupy-cudaXXX or cupy-rocm-X-X), make sure that the package matches with the version of CUDA or ROCm installed.

On Linux, you may need to set LD_LIBRARY_PATH environment variable depending on how you installed CUDA/ROCm.
On Windows, try setting CUDA_PATH environment variable.

Check the Installation Guide for details:
  https://docs.cupy.dev/en/latest/install.html

CUDA Path: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1
DLL dependencies:
  KERNEL32.dll -> C:\WINDOWS\System32\KERNEL32.DLL
  MSVCP140.dll -> C:\WINDOWS\SYSTEM32\msvcp140.dll
  VCRUNTIME140.dll -> C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\VCRUNTIME140.dll
  api-ms-win-crt-convert-l1-1-0.dll -> C:\WINDOWS\System32\ucrtbase.dll
  api-ms-win-crt-environment-l1-1-0.dll -> C:\WINDOWS\System32\ucrtbase.dll
  api-ms-win-crt-filesystem-l1-1-0.dll -> C:\WINDOWS\System32\ucrtbase.dll
  api-ms-win-crt-heap-l1-1-0.dll -> C:\WINDOWS\System32\ucrtbase.dll
  api-ms-win-crt-runtime-l1-1-0.dll -> C:\WINDOWS\System32\ucrtbase.dll
  api-ms-win-crt-stdio-l1-1-0.dll -> C:\WINDOWS\System32\ucrtbase.dll
  cuTENSOR.dll -> not found
  cublas64_11.dll -> not found
  cudart64_110.dll -> not found
  cudnn64_8.dll -> C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\lib\cudnn64_8.dll
  cufft64_10.dll -> not found
  curand64_10.dll -> C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\lib\curand64_10.dll
  cusolver64_11.dll -> C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\lib\cusolver64_11.dll
  cusparse64_11.dll -> not found
  nvcuda.dll -> C:\WINDOWS\SYSTEM32\nvcuda.dll
  nvrtc64_112_0.dll -> not found
  python311.dll -> C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\python311.dll

Original error:
  ImportError: DLL load failed while importing runtime: The specified module could not be found.
================================================================

### Loading: ComfyUI-Impact-Pack (V4.20.3)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.2.4)
### Loading: ComfyUI-Inspire-Pack (V0.28.3)
### Loading: ComfyUI-Manager (V0.34)
### ComfyUI Revision: 1575 [2231edec] | Released on '2023-10-14'


   0.1 seconds (IMPORT FAILED): C:\sdComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation

**Comment by boricuapab** [comment]
Running into same issue was working until I decided to update comfy today to pickup the cuda 12 implementation

```
Checking cupy...
Uninstall cupy if existed...
WARNING: Skipping cupy-wheel as it is not installed.
WARNING: Skipping cupy-cuda102 as it is not installed.
WARNING: Skipping cupy-cuda110 as it is not installed.
WARNING: Skipping cupy-cuda111 as it is not installed.
Found existing installation: cupy-cuda11x 12.2.0
Uninstalling cupy-cuda11x-12.2.0:
  Successfully uninstalled cupy-cuda11x-12.2.0
ERROR: Exception:
Traceback (most recent call last):
  File "C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\commands\uninstall.py", line 110, in run
    uninstall_pathset.commit()
  File "C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\req\req_uninstall.py", line 432, in commit
    self._moved_paths.commit()
  File "C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\req\req_uninstall.py", line 278, in commit
    save_dir.cleanup()
  File "C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\utils\temp_dir.py", line 173, in cleanup
    rmtree(self._path)
  File "C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 291, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 381, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 327, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 160, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "concurrent\futures\_base.py", line 449, in result
  File "concurrent\futures\_base.py", line 401, in __get_result
  File "C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 384, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_internal\utils\misc.py", line 130, in rmtree
    shutil.rmtree(dir, ignore_errors=ignore_errors, onerror=rmtree_errorhandler)
  File "shutil.py", line 759, in rmtree
  File "shutil.py", line 617, in _rmtree_unsafe
  File "shutil.py", line 622, in _rmtree_unsafe
  File "shutil.py", line 620, in _rmtree_unsafe
PermissionError: [WinError 5] Access is denied: 'C:\\sdComfyUI\\ComfyUI_windows_portable\\python_embeded\\Lib\\site-packages\\~~py\\cuda\\device.cp311-win_amd64.pyd'
Installing cupy...
WARNING: Ignoring invalid distribution ~ (C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages)
Collecting cupy-cuda11x
  Obtaining dependency information for cupy-cuda11x from https://files.pythonhosted.org/packages/b2/a9/569c6f4eb5bbd12646befedce5382ddc1e710a0dc4964e7e085f7987529b/cupy_cuda11x-12.2.0-cp311-cp311-win_amd64.whl.metadata
  Using cached cupy_cuda11x-12.2.0-cp311-cp311-win_amd64.whl.metadata (2.7 kB)
Requirement already satisfied: numpy<1.27,>=1.20 in c:\sdcomfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from cupy-cuda11x) (1.25.2)
Requirement already satisfied: fastrlock>=0.5 in c:\sdcomfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from cupy-cuda11x) (0.8.2)
Using cached cupy_cuda11x-12.2.0-cp311-cp311-win_amd64.whl (70.2 MB)
WARNING: Ignoring invalid distribution ~ (C:\sdComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages)
Installing collected packages: cupy-cuda11x
Successfully installed cupy-cuda11x-12.2.0
Press any key to continue . . .

**Comment by Fannovel16** [comment]
@boricuapab Try the latest commit

**Comment by boricuapab** [comment]
Thanks latest commit has fixed the cupy build issue.

```
C:\sdComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation>git log -1
commit 93178b62c7cada0957d8f8ffe557d3087a43de76 (HEAD -> main, origin/main, origin/HEAD)
Author: Hacker 17082006 <tai17082006.tk@gmail.com>
Date:   Sun Oct 15 14:59:02 2023 +0700

    Fix https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/issues/21

```
Checking cupy...
Uninstall cupy if existed...
WARNING: Skipping cupy-wheel as it is not installed.
WARNING: Skipping cupy-cuda102 as it is not installed.
WARNING: Skipping cupy-cuda110 as it is not installed.
WARNING: Skipping cupy-cuda111 as it is not installed.
Found existing installation: cupy-cuda11x 12.2.0
Uninstalling cupy-cuda11x-12.2.0:
  Successfully uninstalled cupy-cuda11x-12.2.0
WARNING: Skipping cupy-cuda12x as it is not installed.
Installing cupy...
Collecting cupy-cuda11x
  Obtaining dependency information for cupy-cuda11x from https://files.pythonhosted.org/packages/b2/a9/569c6f4eb5bbd12646befedce5382ddc1e710a0dc4964e7e085f7987529b/cupy_cuda11x-12.2.0-cp311-cp311-win_amd64.whl.metadata
  Downloading cupy_cuda11x-12.2.0-cp311-cp311-win_amd64.whl.metadata (2.7 kB)
Requirement already satisfied: numpy<1.27,>=1.20 in c:\sdcomfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from cupy-cuda11x) (1.25.2)
Requirement already satisfied: fastrlock>=0.5 in c:\sdcomfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from cupy-cuda11x) (0.8.2)
Downloading cupy_cuda11x-12.2.0-cp311-cp311-win_amd64.whl (70.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.2/70.2 MB 8.8 MB/s eta 0:00:00
Installing collected packages: cupy-cuda11x
Successfully installed cupy-cuda11x-12.2.0
Press any key to continue . . .
