### ISSUE TITLE
FILM VFI Runtime Error TorchScript

### ISSUE THREAD

**Issue by brbbbq** [Fannovel16/ComfyUI-Frame-Interpolation#23]
This node was working fine until yesterday, all of a sudden started getting this runtime error:
![231023-073303-chrome-1](https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/assets/135537138/1021cc6d-1fd2-4e09-b6ab-71bd23363ac9)

Tried reducing the clear cache to 5 frames, but didn't help. Here's my workflow:
![231023-091527-chrome](https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/assets/135537138/02ab8f1e-c8bc-4234-a486-0eb45a82e9c9)

This is the error from the terminal window:
```
!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\Apps\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\Apps\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\Apps\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\Apps\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\film\__init__.py", line 86, in vfi
    relust = inference(model, frames[frame_itr], frames[frame_itr + 1], multiplier - 1)
  File "C:\Apps\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\film\__init__.py", line 35, in inference
    prediction = model(x0, x1, dt)
  File "C:\Apps\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/interpolator.py", line 15, in forward
    x1: Tensor,
    batch_dt: Tensor) -> Tensor:
    _0 = (self).debug_forward(x0, x1, batch_dt, )
          ~~~~~~~~~~~~~~~~~~~ <--- HERE
    return (_0["image"])[0]
  def debug_forward(self: __torch__.interpolator.Interpolator,
  File "code/__torch__/interpolator.py", line 64, in debug_forward
    aligned_pyramid1 = __torch__.util.concatenate_pyramids(aligned_pyramid0, forward_flow, )
    fuse = self.fuse
    _18 = [(fuse).forward(aligned_pyramid1, )]
            ~~~~~~~~~~~~~ <--- HERE
    _19 = {"image": _18, "forward_residual_flow_pyramid": forward_residual_flow_pyramid, "backward_residual_flow_pyramid": backward_residual_flow_pyramid, "forward_flow_pyramid": forward_flow_pyramid, "backward_flow_pyramid": backward_flow_pyramid}
    return _19
  File "code/__torch__/fusion.py", line 56, in forward
    _04 = getattr(_3, "0")
    net16 = (_04).forward(net15, )
    net17 = torch.cat([pyramid[i2], net16], 1)
            ~~~~~~~~~ <--- HERE
    _13 = getattr(_3, "1")
    net18 = (_13).forward(net17, )

Traceback of TorchScript, original code (most recent call last):
  File "C:\Users\Danylo\PycharmProjects\frame-interpolation-pytorch\interpolator.py", line 160, in forward
    @torch.jit.export
    def forward(self, x0, x1, batch_dt) -> torch.Tensor:
        return self.debug_forward(x0, x1, batch_dt)['image'][0]
               ~~~~~~~~~~~~~~~~~~ <--- HERE
  File "C:\Users\Danylo\PycharmProjects\frame-interpolation-pytorch\interpolator.py", line 151, in debug_forward

        return {
            'image': [self.fuse(aligned_pyramid)],
                      ~~~~~~~~~ <--- HERE
            'forward_residual_flow_pyramid': forward_residual_flow_pyramid,
            'backward_residual_flow_pyramid': backward_residual_flow_pyramid,
  File "C:\Users\Danylo\PycharmProjects\frame-interpolation-pytorch\fusion.py", line 116, in forward
            net = F.interpolate(net, size=level_size, mode='nearest')
            net = layers[0](net)
            net = torch.cat([pyramid[i], net], dim=1)
                  ~~~~~~~~~ <--- HERE
            net = layers[1](net)
            net = layers[2](net)
RuntimeError: Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated     : 5.77 GiB
Requested               : 568.12 MiB
Device limit            : 12.00 GiB
Free (according to CUDA): 0 bytes
PyTorch limit (set by user-supplied memory fraction)
                        : 17179869184.00 GiB
```

**Comment by Fannovel16** [comment]
@brbbbq The latest commit just change RIFE's code so it is not related to your issue
https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/commit/ad8dd1f9c6bea3608ea8b8c445c79718ca99df58

1. What is the resolution of your video? If it is something like 1080p, you should downscale it with "Upscale Image By" node (scale_by=0.5 will downscale frames by two times)
2. Did you update your ComfyUI?

**Comment by brbbbq** [comment]
I was able to get it to work again by limiting the number of input frames. The image size is 768x968, I have a 3080ti with 12GB VRAM. I accidentally updated ComfyUI just trying to figure out what version it is. Still don't know what the version number is, it's not listed anywhere that I can find, but apparently it's the most recent one now.

After updating, running the interpolation nodes no longer gives me an OOM error, it just freezes with no error reporting and I have to restart the client, much worse.

Luckily I did discover before updating, that I can run a batch of 105 frames, but any more than that and it hangs. I assumed the frame caching feature would mitigate VRAM usage, is it loading all the frames at once?

Looks like I'm using pytorch v1.13
![Uploading 231023-104237-python.png…]()

**Comment by brbbbq** [comment]
Also want to add, that testing RIFE gave me similar OOM errors, but at larger frame numbers, so it's not isolated to the FILM node. I changed the title of the issue as a result.

**Comment by Fannovel16** [comment]
@brbbbq Update ComfyUI-Frame-Interpolation. My commit doesn't fix the issue but it should help pinpointing where it is.

**Comment by brbbbq** [comment]
Nice, got the error messages back :)
```
got prompt
Comfy-VFI: Clearing cache...
Comfy-VFI: Done cache clearing
Comfy-VFI: Clearing cache...
Comfy-VFI: Done cache clearing
Comfy-VFI: Clearing cache...
Comfy-VFI: Done cache clearing
Comfy-VFI: Clearing cache...
Comfy-VFI: Done cache clearing
Comfy-VFI: Clearing cache...
Comfy-VFI: Done cache clearing
Comfy-VFI: Clearing cache...
Comfy-VFI: Done cache clearing
Comfy-VFI: Clearing cache...
Comfy-VFI: Done cache clearing
Comfy-VFI: Clearing cache...
Comfy-VFI: Done cache clearing
Comfy-VFI: Clearing cache...
Comfy-VFI: Done cache clearing
Comfy-VFI: Clearing cache...
Comfy-VFI: Done cache clearing
Comfy-VFI: Clearing cache...
Comfy-VFI: Done cache clearing
Comfy-VFI: Clearing cache...
Comfy-VFI: Done cache clearing
!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\Apps\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\Apps\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\Apps\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\Apps\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\film\__init__.py", line 86, in vfi
    relust = inference(model, frames[frame_itr], frames[frame_itr + 1], multiplier - 1)
  File "C:\Apps\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\models\film\__init__.py", line 35, in inference
    prediction = model(x0, x1, dt)
  File "C:\Apps\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/interpolator.py", line 15, in forward
    x1: Tensor,
    batch_dt: Tensor) -> Tensor:
    _0 = (self).debug_forward(x0, x1, batch_dt, )
          ~~~~~~~~~~~~~~~~~~~ <--- HERE
    return (_0["image"])[0]
  def debug_forward(self: __torch__.interpolator.Interpolator,
  File "code/__torch__/interpolator.py", line 64, in debug_forward
    aligned_pyramid1 = __torch__.util.concatenate_pyramids(aligned_pyramid0, forward_flow, )
    fuse = self.fuse
    _18 = [(fuse).forward(aligned_pyramid1, )]
            ~~~~~~~~~~~~~ <--- HERE
    _19 = {"image": _18, "forward_residual_flow_pyramid": forward_residual_flow_pyramid, "backward_residual_flow_pyramid": backward_residual_flow_pyramid, "forward_flow_pyramid": forward_flow_pyramid, "backward_flow_pyramid": backward_flow_pyramid}
    return _19
  File "code/__torch__/fusion.py", line 56, in forward
    _04 = getattr(_3, "0")
    net16 = (_04).forward(net15, )
    net17 = torch.cat([pyramid[i2], net16], 1)
            ~~~~~~~~~ <--- HERE
    _13 = getattr(_3, "1")
    net18 = (_13).forward(net17, )

Traceback of TorchScript, original code (most recent call last):
  File "C:\Users\Danylo\PycharmProjects\frame-interpolation-pytorch\interpolator.py", line 160, in forward
    @torch.jit.export
    def forward(self, x0, x1, batch_dt) -> torch.Tensor:
        return self.debug_forward(x0, x1, batch_dt)['image'][0]
               ~~~~~~~~~~~~~~~~~~ <--- HERE
  File "C:\Users\Danylo\PycharmProjects\frame-interpolation-pytorch\interpolator.py", line 151, in debug_forward

        return {
            'image': [self.fuse(aligned_pyramid)],
                      ~~~~~~~~~ <--- HERE
            'forward_residual_flow_pyramid': forward_residual_flow_pyramid,
            'backward_residual_flow_pyramid': backward_residual_flow_pyramid,
  File "C:\Users\Danylo\PycharmProjects\frame-interpolation-pytorch\fusion.py", line 116, in forward
            net = F.interpolate(net, size=level_size, mode='nearest')
            net = layers[0](net)
            net = torch.cat([pyramid[i], net], dim=1)
                  ~~~~~~~~~ <--- HERE
            net = layers[1](net)
            net = layers[2](net)
RuntimeError: Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated     : 5.84 GiB
Requested               : 568.12 MiB
Device limit            : 12.00 GiB
Free (according to CUDA): 0 bytes
PyTorch limit (set by user-supplied memory fraction)
                        : 17179869184.00 GiB


Prompt executed in 90.25 seconds
```

Looks like it fails on the 12th batch, though in my tests I would get failure at 110 frames. I'm guessing it's because it needs to repeat the last frame, so each batch is actually 9 frames? (9 frames x 12 batches = 108 frames).

My Comfyui PyTorch version is 2.0.1:
![231023-152452-cmd](https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/assets/135537138/2bd8764d-a8b9-4ed6-af04-f4178d942288)

Is this something that looks fixable from your end? I'm currently trying to develop a more automated workflow to process the sequence in batches using image batch nodes.

**Comment by brbbbq** [comment]
Here's a ComfyUI workflow for doing batches with FILM:
[2310232-FILM_batch_workflow-01.json](https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/files/13079888/2310232-FILM_batch_workflow-01.json)
![231023-190408-chrome](https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/assets/135537138/1cd10e61-c75f-4e45-8340-be6ac45cf67e)

That's as far as I can get without knowing how to code and do conditional statements. You can repeat the 'Batch 1' group and rewire a few things to expand it for larger batches.

Simply displaying the cache clearing operations was actually really helpful. Being able to know when it fails makes it much easier to calculate the right batch sizes. Another thing I noticed, when increasing the multiplier on the FILM node, requires decreasing the batch size to compensate, as far as I can tell.
![231023-185819-cmd-1](https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/assets/135537138/c1436146-d3cf-40e7-a31d-b42fe66458ea)

**Comment by Fannovel16** [comment]
> Is this something that looks fixable from your end?

Yes. My idea is that all frames are cached in CPU and only moves a certain part to GPU

**Comment by brbbbq** [comment]
For me personally, I think FILM is the best quality that I've seen so far, so I'm happy to use that. 

In regards to the memory error. When I separate the FILM VFI node into batches it works. I'm guessing something inbetween stopping the FILM VFI node and starting a new one, is causing the memory to be cleared out correctly.

**Comment by Fannovel16** [comment]
@brbbbq Can you try the latest commit (https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/commit/f19c7230cb883bf08a6dfb3e2099e75a51fa3318)?

**Comment by brbbbq** [comment]
I grabbed the latest version and ran a large job. Works great! Looks like the memory is getting cleared correctly. Here's an updated workflow with looping:
![231102-FILM_interpolation_with_looping](https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/assets/135537138/69f2a70b-a7ad-46cc-94e3-6de0d31c1bd8)

Thanks for fixing it!

**Comment by drmbt** [comment]
> I grabbed the latest version and ran a large job. Works great! Looks like the memory is getting cleared correctly. Here's an updated workflow with looping: ![231102-FILM_interpolation_with_looping](https://private-user-images.githubusercontent.com/135537138/280032920-69f2a70b-a7ad-46cc-94e3-6de0d31c1bd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNjkzMzUsIm5iZiI6MTcyMjI2OTAzNSwicGF0aCI6Ii8xMzU1MzcxMzgvMjgwMDMyOTIwLTY5ZjJhNzBiLWE3YWQtNDZjYy05NGUzLTZkZTBkMzFjMWJkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOVQxNjAzNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNjYxZDQxMjg2MmNhMWRkZDFiNDcyMThmMjZlOWVhNjlmOTc0NzAyMzYyNWI2ZDlhZDBkNDIwMjEzZDQ3NDJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kb8X6AFEvuvPqtD7a-OxQ0-5DQBjsc5v1ph34iN7XEc)
> 
> Thanks for fixing it!

any chance you could make this workflow public?
