### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by blueroutecn** [Fannovel16/ComfyUI-Frame-Interpolation#27]
I run workflow, and show this info:

Downloading: "https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/GMFSS_fortuna_union_fusionnet.pkl" to /home/llm/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation/ckpts/gmfss_fortuna/GMFSS_fortuna_union_fusionnet.pkl

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30.0M/30.0M [01:48<00:00, 291kB/s]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/home/llm/ComfyUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/llm/ComfyUI/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/llm/ComfyUI/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/llm/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation/models/gmfss_fortuna/__init__.py", line 128, in vfi
    interpolation_model = CommonModelInference(model_type=ckpt_name)
  File "/home/llm/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation/models/gmfss_fortuna/__init__.py", line 36, in __init__
    self.model.load_model({
  File "/home/llm/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation/models/gmfss_fortuna/GMFSS_Fortuna_union_arch.py", line 1716, in load_model
    self.ifnet.load_state_dict(torch.load(path_dict["ifnet"]))
  File "/home/llm/ComfyUI/myenv/lib/python3.10/site-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/llm/ComfyUI/myenv/lib/python3.10/site-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by Fannovel16** [comment]
@blueroutecn The pkl file downloaded is corruputed. Go to `/home/llm/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation/ckpts` and delete `gmfss_fortuna` folder to force redownloading

**Comment by rish** [comment]
Alternatively, you can download them manually from here:

https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/tag/models

**Comment by blueroutecn** [comment]
Thx
