### ISSUE TITLE
Error on import: No module named 'models.gmfss_fortuna'

### ISSUE THREAD

**Issue by rbhuta** [Fannovel16/ComfyUI-Frame-Interpolation#29]
### ComfyUI Revision: 1661 [064d7583] | Released on '2023-11-08'
Traceback (most recent call last):
  File "/home/ComfyUI/nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation/__init__.py", line 9, in <module>
    from models.gmfss_fortuna import GMFSS_Fortuna_VFI
ModuleNotFoundError: No module named 'models.gmfss_fortuna'

Cannot import /home/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation module for custom nodes: No module named 'models.gmfss_fortuna'

Import times for custom nodes:
   0.1 seconds (IMPORT FAILED): /home/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation
   
 Installed today and getting an import error. Installed repo through Comfy Manager. Any ideas what might be wrong? @Fannovel16

**Comment by GentlemanHu** [comment]
same here

```python
Traceback (most recent call last):
  File "/content/drive/colab_ai/ComfyUI/nodes.py", line 1752, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/drive/colab_ai/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation/__init__.py", line 9, in <module>
    from models.gmfss_fortuna import GMFSS_Fortuna_VFI
ModuleNotFoundError: No module named 'models.gmfss_fortuna'

Cannot import /content/drive/colab_ai/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation module for custom nodes: No module named 'models.gmfss_fortuna'
```

**Comment by Fannovel16** [comment]
@rbhuta @GentlemanHu Fixed in https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/commit/4f60bf5c04149b3158b8739aff27bdafd5ac9703. Update/Reinstall ComfyUI-Frame-Interpolation and it should works now
