### ISSUE TITLE
Error occurred when executing RIFE VFI:  Tried all GitHub base urls to download rife47.pth but no suceess. 

### ISSUE THREAD

**Issue by joshalanwagner** [Fannovel16/ComfyUI-Frame-Interpolation#54]
I was able to download rife47.pth from the url, but no idea where it's looking for it. 

> Error occurred when executing RIFE VFI:

Tried all GitHub base urls to download rife47.pth but no suceess. Below is the error log:

Error when downloading from: https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/rife47.pth

Traceback (most recent call last):
File "urllib\request.py", line 1348, in do_open
File "http\client.py", line 1283, in request
File "http\client.py", line 1329, in _send_request
File "http\client.py", line 1278, in endheaders
File "http\client.py", line 1038, in _send_output
File "http\client.py", line 976, in send
File "http\client.py", line 1455, in connect
File "ssl.py", line 513, in wrap_socket
File "ssl.py", line 1071, in _create
File "ssl.py", line 1342, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\Josh\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\vfi_utils.py", line 100, in load_file_from_github_release
return load_file_from_url(base_model_download_url + ckpt_name, get_ckpt_container_path(model_type))
File "C:\Users\Josh\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\vfi_utils.py", line 93, in load_file_from_url
download_url_to_file(url, cached_file, hash_prefix=None, progress=progress)
File "C:\Users\Josh\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\hub.py", line 620, in download_url_to_file
u = urlopen(req)
File "urllib\request.py", line 216, in urlopen
File "urllib\request.py", line 519, in open
File "urllib\request.py", line 536, in _open
File "urllib\request.py", line 496, in _call_chain
File "urllib\request.py", line 1391, in https_open
File "urllib\request.py", line 1351, in do_open
urllib.error.URLError:

Error when downloading from: https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/releases/download/models/rife47.pth

Traceback (most recent call last):
File "urllib\request.py", line 1348, in do_open
File "http\client.py", line 1283, in request
File "http\client.py", line 1329, in _send_request
File "http\client.py", line 1278, in endheaders
File "http\client.py", line 1038, in _send_output
File "http\client.py", line 976, in send
File "http\client.py", line 1455, in connect
File "ssl.py", line 513, in wrap_socket
File "ssl.py", line 1071, in _create
File "ssl.py", line 1342, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\Josh\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\vfi_utils.py", line 100, in load_file_from_github_release
return load_file_from_url(base_model_download_url + ckpt_name, get_ckpt_container_path(model_type))
File "C:\Users\Josh\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\vfi_utils.py", line 93, in load_file_from_url
download_url_to_file(url, cached_file, hash_prefix=None, progress=progress)
File "C:\Users\Josh\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\hub.py", line 620, in download_url_to_file
u = urlopen(req)
File "urllib\request.py", line 216, in urlopen
File "urllib\request.py", line 519, in open
File "urllib\request.py", line 536, in _open
File "urllib\request.py", line 496, in _call_chain
File "urllib\request.py", line 1391, in https_open
File "urllib\request.py", line 1351, in do_open
urllib.error.URLError:

Error when downloading from: https://github.com/dajes/frame-interpolation-pytorch/releases/download/v1.0.0/rife47.pth

Traceback (most recent call last):
File "urllib\request.py", line 1348, in do_open
File "http\client.py", line 1283, in request
File "http\client.py", line 1329, in _send_request
File "http\client.py", line 1278, in endheaders
File "http\client.py", line 1038, in _send_output
File "http\client.py", line 976, in send
File "http\client.py", line 1455, in connect
File "ssl.py", line 513, in wrap_socket
File "ssl.py", line 1071, in _create
File "ssl.py", line 1342, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\Josh\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\vfi_utils.py", line 100, in load_file_from_github_release
return load_file_from_url(base_model_download_url + ckpt_name, get_ckpt_container_path(model_type))
File "C:\Users\Josh\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\vfi_utils.py", line 93, in load_file_from_url
download_url_to_file(url, cached_file, hash_prefix=None, progress=progress)
File "C:\Users\Josh\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\hub.py", line 620, in download_url_to_file
u = urlopen(req)
File "urllib\request.py", line 216, in urlopen
File "urllib\request.py", line 519, in open
File "urllib\request.py", line 536, in _open
File "urllib\request.py", line 496, in _call_chain
File "urllib\request.py", line 1391, in https_open
File "urllib\request.py", line 1351, in do_open
urllib.error.URLError:

File "C:\Users\Josh\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\Users\Josh\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\Users\Josh\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "C:\Users\Josh\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\vfi_models\rife\__init__.py", line 90, in vfi
model_path = load_file_from_github_release(MODEL_TYPE, ckpt_name)
File "C:\Users\Josh\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\vfi_utils.py", line 108, in load_file_from_github_release
raise Exception(f"Tried all GitHub base urls to download {ckpt_name} but no suceess. Below is the error log:\n\n{error_str}")

Close
Queue size: 0
⚙️
🖼️
×
Queue Prompt
Extra options
Queue FrontView QueueView History
Save
Load
Refresh
Clipspace
Clear
Load Default
Manager
Share

**Comment by joshalanwagner** [comment]
I tried to use M2M, but it seems like this file no longer exists:

https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/download/models/M2M.pth

**Comment by Fannovel16** [comment]
@joshalanwagner I uploaded M2M to my [mirror](https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/releases/tag/models). It should work now without the need to update

**Comment by qwaaws** [comment]
rife47.pth放到ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\ckpts\rife
