### ISSUE TITLE
Unable to detect NVIDIA CUDA or AMD ROCm installation.

### ISSUE THREAD

**Issue by dlandry** [Fannovel16/ComfyUI-Frame-Interpolation#57]
Got some errors during install, but the installation in the end said it installed successfully, so not sure what that really means?

A restart didn't so any issues in the restart process, just the install. So not sure how critical this is? (I am able to install other custome nodes with not isse - see below!

Install custom node 'ComfyUI Frame Interpolation'
install: ['https://github.com/Fannovel16/ComfyUI-Frame-Interpolation']
Download: git clone 'https://github.com/Fannovel16/ComfyUI-Frame-Interpolation'
100%|██████████| 534.0/534.0 [00:06<00:00, 85.51it/s] 
Install: install script

## ComfyUI-Manager: EXECUTE => ['/var/home/david/Documents/AITools/ComfyUI/.venv/bin/python', 'install.py']
                         Collecting opencv-contrib-python
   Downloading opencv_contrib_python-4.9.0.80-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (68.3 MB)
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.3/68.3 MB 19.4 MB/s eta 0:00:00
  Installing collected packages: opencv-contrib-python
 Successfully installed opencv-contrib-python-4.9.0.80
                                                      [!] WARNING: Skipping cupy-wheel as it is not installed.
[!] WARNING: Skipping cupy-cuda102 as it is not installed.
[!] WARNING: Skipping cupy-cuda110 as it is not installed.
[!] WARNING: Skipping cupy-cuda111 as it is not installed.
[!] WARNING: Skipping cupy-cuda11x as it is not installed.
[!] WARNING: Skipping cupy-cuda12x as it is not installed.
 Collecting cupy-wheel
   Downloading cupy-wheel-12.3.0.tar.gz (2.9 kB)
   Preparing metadata (setup.py): started
   Preparing metadata (setup.py): finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]   
[!]   × python setup.py egg_info did not run successfully.
[!]   │ exit code: 1
[!]   ╰─> [30 lines of output]
[!]       [cupy-wheel] Trying to detect CUDA version from libraries: ['libnvrtc.so.12', 'libnvrtc.so.11.2', 'libnvrtc.so.11.1', 'libnvrtc.so.11.0', 'libnvrtc.so.10.2']
[!]       [cupy-wheel] Looking for library: libnvrtc.so.12
[!]       [cupy-wheel] Failed to open libnvrtc.so.12: libnvrtc.so.12: cannot open shared object file: No such file or directory
[!]       [cupy-wheel] Looking for library: libnvrtc.so.11.2
[!]       [cupy-wheel] Failed to open libnvrtc.so.11.2: libnvrtc.so.11.2: cannot open shared object file: No such file or directory
[!]       [cupy-wheel] Looking for library: libnvrtc.so.11.1
[!]       [cupy-wheel] Failed to open libnvrtc.so.11.1: libnvrtc.so.11.1: cannot open shared object file: No such file or directory
[!]       [cupy-wheel] Looking for library: libnvrtc.so.11.0
[!]       [cupy-wheel] Failed to open libnvrtc.so.11.0: libnvrtc.so.11.0: cannot open shared object file: No such file or directory
[!]       [cupy-wheel] Looking for library: libnvrtc.so.10.2
[!]       [cupy-wheel] Failed to open libnvrtc.so.10.2: libnvrtc.so.10.2: cannot open shared object file: No such file or directory
[!]       [cupy-wheel] No more candidate library to find
[!]       [cupy-wheel] Looking for library: libamdhip64.so
[!]       [cupy-wheel] Failed to open libamdhip64.so: libamdhip64.so: cannot open shared object file: No such file or directory
[!]       [cupy-wheel] No more candidate library to find
[!]       Traceback (most recent call last):
[!]         File "<string>", line 2, in <module>
[!]         File "<pip-setuptools-caller>", line 34, in <module>
[!]         File "/tmp/pip-install-yq5cnx0z/cupy-wheel_7ab29a1e67f14da0adc5114ee40ed9c2/setup.py", line 285, in <module>
[!]           main()
[!]         File "/tmp/pip-install-yq5cnx0z/cupy-wheel_7ab29a1e67f14da0adc5114ee40ed9c2/setup.py", line 269, in main
[!]           package = infer_best_package()
[!]                     ^^^^^^^^^^^^^^^^^^^^
[!]         File "/tmp/pip-install-yq5cnx0z/cupy-wheel_7ab29a1e67f14da0adc5114ee40ed9c2/setup.py", line 259, in infer_best_package
[!]           raise AutoDetectionFailed(
[!]       AutoDetectionFailed:
[!]       ============================================================
[!]       Unable to detect NVIDIA CUDA or AMD ROCm installation.
[!]       ============================================================
[!]       
[!]       [end of output]
[!]   
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!] error: metadata-generation-failed
[!] 
[!] × Encountered error while generating package metadata.
[!] ╰─> See above for output.
[!] 
[!] note: This is an issue with the package mentioned above, not pip.
[!] hint: See above for details.
 Installing torch...
 Installing numpy...
 Installing einops...
 Installing opencv-contrib-python...
 Installing kornia...
 Installing scipy...
 Installing Pillow...
 Installing torchvision...
 Installing tqdm...
 Checking cupy...
 Uninstall cupy if existed...
 Installing cupy...
Installation was successful.
After restarting ComfyUI, please refresh the browser.
FETCH DATA from: /var/home/david/Documents/AITools/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/1514988643_custom-node-list.json
FETCH DATA from: /var/home/david/Documents/AITools/ComfyUI/custom_nodes/ComfyUI-Manager/.cache/1742899825_extension-node-map.json
** ComfyUI startup time: 2024-04-10 19:45:09.229422
** Platform: Linux
** Python version: 3.11.0rc1 (main, Aug 12 2022, 10:02:14) [GCC 11.2.0]
** Python executable: /var/home/david/Documents/AITools/ComfyUI/.venv/bin/python
** Log path: /var/home/david/Documents/AITools/ComfyUI/comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: /var/home/david/Documents/AITools/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 16072 MB, total RAM 63969 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti SUPER : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
### ComfyUI Revision: 2120 [4201181b] | Released on '2024-04-09'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
[Crystools INFO] Crystools version: 1.12.0
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[Crystools INFO] CPU: 13th Gen Intel(R) Core(TM) i9-13900K - Arch: x86_64 - OS: Linux 6.8.4-200.fc39.x86_64
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 4070 Ti SUPER
[Crystools INFO] NVIDIA Driver: 550.67
Note: NumExpr detected 32 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
FizzleDorf Custom Nodes: Loaded

Import times for custom nodes:
   0.0 seconds: /var/home/david/Documents/AITools/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds: /var/home/david/Documents/AITools/ComfyUI/custom_nodes/ComfyUI-Crystools-save
   0.0 seconds: /var/home/david/Documents/AITools/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
   0.0 seconds: /var/home/david/Documents/AITools/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet
   0.0 seconds: /var/home/david/Documents/AITools/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved
   0.0 seconds: /var/home/david/Documents/AITools/ComfyUI/custom_nodes/ComfyUI_essentials
   0.0 seconds: /var/home/david/Documents/AITools/ComfyUI/custom_nodes/aegisflow_utility_nodes
   0.0 seconds: /var/home/david/Documents/AITools/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation
   0.1 seconds: /var/home/david/Documents/AITools/ComfyUI/custom_nodes/ComfyUI-Manager
   0.1 seconds: /var/home/david/Documents/AITools/ComfyUI/custom_nodes/ComfyUI_FizzNodes
   0.1 seconds: /var/home/david/Documents/AITools/ComfyUI/custom_nodes/comfy_PoP
   0.2 seconds: /var/home/david/Documents/AITools/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes
   2.1 seconds: /var/home/david/Documents/AITools/ComfyUI/custom_nodes/ComfyUI-Crystools

Starting server

To see the GUI go to: http://127.0.0.1:8188
---------------------

I was doing a fresh install and installing old custom_nodes one at a time and monitoring:

This is where I was when I ran into the error:

[x ]  [[aegisflow_utility_nodes]]
[x ]  [[comfy_PoP]]
[x ]  [[ComfyUI-Advanced-ControlNet]]
[x ]  [[ComfyUI-AnimateDiff-Evolved]]
[x ]  [[ComfyUI_Comfyroll_CustomNodes]]
[x ]  [[comfyui_controlnet_aux]]  ** Didn't install yet ... too many conflicts with ComfyUI-Advanced-ControlNet
[x ]  [[ComfyUI-Crystools]]
[x ] [[ComfyUI-Crystools-save]]
[x ]  [[ComfyUI-Custom-Scripts]]
[* ]  [[ComfyUI-Eagle-PNGInfo]] ** not going to use. Will use SDXL_Prompt_Styler instead
[x ]  [[ComfyUI_essentials]]
[x ]  [[ComfyUI_FizzNodes]]
[ ]  [[ComfyUI-Frame-Interpolation]]

**Comment by Mortorojo** [comment]
Something is wrong with cupy-wheel. A workaround is to manually install your CUDA version of cupy.
I think you have are on CUDA 12.5 w/ 4070 Ti SU, use:
`pip install cupy-cuda12x`
See [https://docs.cupy.dev/en/stable/install.html](url)
