### ISSUE TITLE
stmfnet.pth Error 404 - link down

### ISSUE THREAD

**Issue by Milor123** [Fannovel16/ComfyUI-Frame-Interpolation#71]
Hi guys i am trying running a workflow with it
![image](https://github.com/user-attachments/assets/6ae39251-969e-4140-b352-3ef7ec333498)

But the nodes cant download the model, is it outdated? should i change the node?

What files should I download from here https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/releases/tag/models and where should i put it files?

Thank u very much

```
Error when downloading from: https://github.com/Fannovel16/ComfyUI-Frame-Interpolation/releases/download/models/stmfnet.pth

Traceback (most recent call last):
  File "/home/noe/Documentos/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation/vfi_utils.py", line 100, in load_file_from_github_release
    return load_file_from_url(base_model_download_url + ckpt_name, get_ckpt_container_path(model_type))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noe/Documentos/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation/vfi_utils.py", line 93, in load_file_from_url
    download_url_to_file(url, cached_file, hash_prefix=None, progress=progress)
  File "/home/noe/.pyenv/versions/3.11.7/envs/Comfyv3/lib/python3.11/site-packages/torch/hub.py", line 622, in download_url_to_file
    u = urlopen(req)
        ^^^^^^^^^^^^
  File "/home/noe/.pyenv/versions/3.11.7/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noe/.pyenv/versions/3.11.7/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/noe/.pyenv/versions/3.11.7/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/home/noe/.pyenv/versions/3.11.7/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noe/.pyenv/versions/3.11.7/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/home/noe/.pyenv/versions/3.11.7/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by devniel** [comment]
I think it should be this: https://huggingface.co/camenduru/stmfnet/blob/d01bfe71879a254c99325efda89c2ac5d465ca28/stmfnet.pth

**Comment by Aljnk** [comment]
this `stmfnet.pth` not work for me  - 

File "\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation\vfi_models\stmfnet\__init__.py", line 52, in vfi
    model.load_state_dict(torch.load(model_path))
  File "\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for STMFNet_Model:
        Missing key(s) in state_dict: "gauss_kernel", "feature_extractor.conv1.resnext_small.conv1.weight", "feature_extractor.conv1.resnext_small.bn1.weight",........
